### PR TITLE
feature dark mode added

### PR DESCRIPTION
**Pull request by KashyapPavra**
The following changes have been performed to add Dark Mode feature

## Dark Mode Toggle button and header

```html
<body id="mainBody" class="justify-content-center">
<div id="mainWindow" class="small-container border border-dark mainWindow">
        <h1 class="h3 d-inline mb-3 font-weight-normal">Add a meeting</h1>
```
``mainBody`` and ``mainWindow`` id added to identify in javascript logic

``Add a Meeting`` made inline using bootstrap class `d-inline`

## Dark Mode Button which triggers darkModeToggle() function
```html
 <button class="dark-theme-btn" onclick="darkModeToggle()">Dark Mode</button>
```

## Dark Mode Toggle Function

Added ``darkModeToggle()`` function which toggles dark-theme class for body and border-dark class for mainWindow
```javascript
function darkModeToggle(){
    document.getElementById('mainBody').classList.toggle("dark-theme");
    document.getElementById('mainWindow').classList.toggle("border-dark");
}
```
## Text muted class changed
```html
 <p class="card-text"><small class="text-muted-custom">${element.link}</small></p>
```
Created a custom class ``text-muted-custom`` as bootstrap had `` !important ``set for its color attribute, so switching color in dark mode was not possible

## Style changes

Toggling dark-theme with these classes, giving transition of 0.5 seconds
```css
.dark-theme-btn {
  border: 1px solid #333333;
  border-radius: 10px;
  background-color: #333333;
  color: #ffffff;
  padding: 10px;
  margin: 10px 0px;
  float: right;
  transition: 0.5s all;
}
body.dark-theme .dark-theme-btn {
  transition: 0.5s all;
  border: 1px solid #ffffff;
  background-color: #ffffff;
  color: #333333;
}
body.dark-theme,
body.dark-theme input,
body.dark-theme .card {
  transition: 0.5s all;
  background-color: #333333;
  color: #ffffff;
}

body.dark-theme .card {
  transition: 0.5s all;
  border: #ffffff 1px solid;
}

body.dark-theme #credits,
body.dark-theme .text-muted-custom {
  transition: 0.5s all;
  color: #ffffff;
}

.text-muted-custom {
  transition: 0.5s all;
  color: #6c757d;
}

body.dark-theme input {
  transition: 0.5s all;
  border-color: #ffffff;
}

body.dark-theme input::placeholder {
  /* Chrome, Firefox, Opera, Safari 10.1+ */
  transition: 0.5s all;
  color: #ffffff;
  opacity: 0.8; /* Firefox */
}

body.dark-theme input:-ms-input-placeholder {
  /* Internet Explorer 10-11 */
  transition: 0.5s all;
  color: #ffffff;
}

body.dark-theme input::-ms-input-placeholder {
  /* Microsoft Edge */
  transition: 0.5s all;
  color: #ffffff;
}
```

### CODE REVIEW

**Comment by virejdasani** [comment]
@KashyapPavra, thanks a lot!

**Comment by virejdasani** [comment]
It looks amazing! 👍

**Comment by virejdasani** [comment]
Also, @KashyapPavra , I was wondering if it is possible for you to change the text inside the button after clicking it to say 'Light Mode'? Because right now, even if it is in dark mode, the button still says dark mode.

**Comment by KashyapPavra** [comment]
@virejdasani Yeah it's possible by changing `innerHTML` of the button in js. I'll make another PR to make that change

**Comment by virejdasani** [comment]
Thanks a bunch. Also, is there a way to default to the dark mode when the app is opened?

**Comment by KashyapPavra** [comment]
Yeah we can default it if we keep the ``dark-theme`` class in body. But we can also set it according to a users device preference in css using ``prefers-color-scheme``
Let me know if you want to default it to dark or should I let the user device decide it

**Comment by virejdasani** [comment]
@KashyapPavra, I think it would be better if we let the user decide the theme, but when opening the app for the first time, I think it will look better in the dark theme.
So by default, it will be set to dark unless the user changes it to light.

**Comment by KashyapPavra** [comment]
Ok, I'll set it default to dark

**Pull request merged**
